// Mocks generated by Mockito 5.4.6 from annotations
// in friend_tracker/test/unit/repositories/location_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:friend_tracker/data/services/firestore_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService extends _i1.Mock implements _i2.FirestoreService {
  MockFirestoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> setLocation(String? userId, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#setLocation, [userId, data]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setSharing(String? userId, bool? isSharing) =>
      (super.noSuchMethod(
            Invocation.method(#setSharing, [userId, isSharing]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<Map<String, dynamic>>> watchFriendsLocations(
    String? myUserId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchFriendsLocations, [myUserId]),
            returnValue: _i3.Stream<List<Map<String, dynamic>>>.empty(),
          )
          as _i3.Stream<List<Map<String, dynamic>>>);

  @override
  _i3.Future<void> sendFriendRequest({
    required String? id,
    required String? fromUserId,
    required String? fromDisplayName,
    required String? toUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendFriendRequest, [], {
              #id: id,
              #fromUserId: fromUserId,
              #fromDisplayName: fromDisplayName,
              #toUserId: toUserId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<Map<String, dynamic>>> watchIncomingRequests(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchIncomingRequests, [userId]),
            returnValue: _i3.Stream<List<Map<String, dynamic>>>.empty(),
          )
          as _i3.Stream<List<Map<String, dynamic>>>);

  @override
  _i3.Stream<List<Map<String, dynamic>>> watchFriends(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchFriends, [userId]),
            returnValue: _i3.Stream<List<Map<String, dynamic>>>.empty(),
          )
          as _i3.Stream<List<Map<String, dynamic>>>);

  @override
  _i3.Future<void> updateRequestStatus(String? requestId, String? status) =>
      (super.noSuchMethod(
            Invocation.method(#updateRequestStatus, [requestId, status]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
